import React from "react";
import Image from "next/image";
import Head from "next/head";
const Page = ({ movies }) => {
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Movies:page
      {movies.map((movies) => (
        <div style={{ display: "flex" }} key={movies.id}>
          <Image
            src={movies.Images[0]}
            alt={movies.Title}
            width="256"
            height="170"
          />
          <h1>{movies.Title}</h1>
        </div>
      ))}
    </div>
  );
};

export async function getServerSideProps() {
  let res = await fetch(`http://localhost:8080/movies`);
  let data = await res.json();
  return {
    props: {
      movies: data,
    },
  };
}

export default Page;
