import React from "react";
import Head from "next/head";
import Link from "next/link";
import Router, { useRouter } from "next/router";
const Page = ({ blogs }) => {
  const router = useRouter();
  const handleCLick = (id) => {
    console.log(id);
    router.push(`/${id}`);
  };
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {blogs.map((blog) => (
          <div key={blog.id}>
            <h1 onClick={() => handleCLick(blog.id)}>{blog.tittle}</h1>
          </div>
        ))}
      </div>
    </>
  );
};

export async function getServerSideProps() {
  let res = await fetch(`http://localhost:8080/blogs`);
  let data = await res.json();
  return {
    props: {
      blogs: data,
    },
  };
}

export default Page;
