import { Heading } from "@chakra-ui/react";
import Head from "next/head";
const Todo = ({ todos }) => {
  return (
    <>
      <div>
        <Head>
          <title>Todo</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Todo</h1>
        {todos.map((el) => {
          return (
            <div key={el.id}>
              <Heading>
                {el.task} ----- {el.isCompleted}
              </Heading>
            </div>
          );
        })}
      </div>
    </>
  );
};

export async function getServerSideProps() {
  try {
    let res = await fetch(`http://localhost:8080/todos`);
    let data = await res.json();
    return {
      props: {
        todos: data,
      },
    };
  } catch (error) {
    console.log("error:", error);
  }
}

export default Todo;
